### PR TITLE
Add Gorilla Talks slides

### PR DESCRIPTION
**Pull request by buddy-sandidge**

### CODE REVIEW

**Comment by tebeka** [comment]
Thanks Buddy. Busy moving out, will do it next week ...

**Comment by buddy-sandidge** [comment]
No worries, whenever you get a chance. Good luck with the move

**Comment by tebeka** [comment]
Thanks

**Comment by tebeka** [comment]
If I would remembered that it's just one button click - I would have done it earlier :smile:

**Pull request merged**
